### PR TITLE
Add image

### PR DESCRIPTION
**Pull request by lwinfree**
Please check Nicole :)

### CODE REVIEW

**Comment by jmcmurry** [comment]
can you please try using this one? Lemme know if aspect ratio needs to be different.
monarch nar cover_2018-05-01

**Comment by lwinfree** [comment]
@jmcmurry Here is a screenshot of what that image looks like as background. Note that there is a Monarch logo that would need to be removed. Also, I removed the OHSU & OSU text because it went on top of the image and couldn't be read.
screen shot 2018-06-18 at 4 21 16 pm

Here is a screenshot of the other background option.
screen shot 2018-06-18 at 2 27 16 pm

I personally like the blue background as I think it is cleaner/less busy, and I'm a little worried about using the map image as I associate it closely with Monarch (and TISL isn't solely Monarch as far as I know).

What do you think? CC @nicolevasilevsky

**Comment by nicolevasilevsky** [comment]
Personally, I like both of them!

**Comment by mellybelly** [comment]
I think I like the subway map one better, i don't think it needs to be monarch-specific. tislab is much more than monarch, but it still largely uses semantics to connect those things.

**Comment by putmantime** [comment]
I like the subway map as well.  Currently it looks a little artificially cut off in my opinion.  Wondering if there is a way to more fluidly ease the transition into the text/links/content.

**Comment by TomConlin** [comment]
Subway, as Tim points out, the foreshortening is a bit abrupt

**Comment by lwinfree** [comment]
Alright sounds like subway is the winner! @jmcmurry could you please send me the image without the Monarch logo? I should be able to resize it myself so that it doesn't get cutoff on the site.
Thanks!

**Comment by jmcmurry** [comment]
monarch nar cover_2018-06-20
See if this works; I also trimmed from top instead.

**Comment by nicolevasilevsky** [comment]
@jmcmurry I don't think the problem is the image, it's the way the screen resizes, @DoctorBud commented about this on another PR. @lwinfree is aware of this and will work to fix it.

**Comment by lwinfree** [comment]
Yes I'll fix it today :) It looks *great* on my screen, which is apparently smaller than others! Always good to have a second set of eyes :)

**Pull request closed without merging**
