### PR TITLE
Create faq.html

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
address https://github.com/tis-lab/tislab.org/issues/71

### CODE REVIEW

**Comment by nicolevasilevsky** [comment]
note, need to add FAQ to the nav on the research page @oneilsh. I didn't want to create a conflict with you

**Comment by monicacecilia** [comment]
Let me know when this stabilizes and I'll check. :)

**Comment by nicolevasilevsky** [comment]
ready for your review, thank you!

**Review by monicacecilia — APPROVED** [review]
:bowtie:

**Pull request merged**
