### PR TITLE
pull in updates from template

### PR DESCRIPTION
**Pull request by vincerubinetti**
Since I created this Tislab.org from the Lab Website Template, there have been many updates to the template. This PR pulls in the updates into this website.

Please give the code and the preview a sanity check to make sure everything looks the same.

### CODE REVIEW

**Comment by nicolevasilevsky** [comment]
Hi @vincerubinetti could you share the preview link?
I'm not the best person to review the code because I'm not a programmer.

I've been meaning to tell you though- you have done such an awesome job with this website, I am super impressed and it looks fantastic. I am grateful for all of your help with it.

**Comment by vincerubinetti** [comment]
Sorry, Netlify is taking its sweet time building the preview. It should show up as a comment on this PR in a minute.

Thanks for your kind words. Also you can just skim the code, or you don't have to. The biggest thing I need is for one or more people from the lab to just review the preview to make sure this PR didn't break any pages or content.

**Comment by nicolevasilevsky** [comment]
I can do that! I'll preview the site when the link becomes available. :)

**Comment by nicolevasilevsky** [comment]
@vincerubinetti looks like our individual team member pages are not displaying correctly: https://deploy-preview-34--tislab-website.netlify.app/members/nicole-vasilevsky.html

**Review by nicolevasilevsky — CHANGES_REQUESTED** [review]
Just the individual team members pages need to be fixed. Everything else looks fine as far as I can see

**Comment by vincerubinetti** [comment]
Good catch, fixed. There were several files that didn't get auto-merge-conflict-resolved properly.

**Comment by nicolevasilevsky** [comment]
Would it be possible to resize the photos so they are all the same size?
For example, Moni's is really big: https://deploy-preview-34--tislab-website.netlify.app/members/monica-munoz-torres.html

Thank you!

**Comment by jmcmurry** [comment]
I don't know how @monicacecilia feels about the 's or s' but perhaps in the fullness of time, she can reply with her preference. Not sure if it affects anyone else.

image

**Comment by jmcmurry** [comment]
Aside from the photo resizing, this looks terrific. Thanks @vincerubinetti !

**Review by jmcmurry — CHANGES_REQUESTED** [review]
Please unify photo size, else looks great thanks.

**Comment by vincerubinetti** [comment]
> I don't know how @monicacecilia feels about the 's or s' but perhaps in the fullness of time, she can reply with her preference. Not sure if it affects anyone else.
> 
> image

This section is irrelevant anyway because tislab does not have a research page like [the greenelab does](https://greenelab.com/research/), so I've removed it.

**Comment by vincerubinetti** [comment]
For posterity:

This PR broke redirects because this line was accidentally removed in the merge: 
`<script src="redirect.js"></script>`
https://github.com/tis-lab/tislab.org/pull/34/files#diff-e241bda4e3c3c6dc1c0b00185b61f6ce19b5eb16e294dd955ca9fa6d01befb0eL2

This commit adds a PR review checklist to remind anyone making a PR to check that redirects still work with the Netlify preview:
https://github.com/tis-lab/tislab.org/commit/aa7671f6c38a392dba2a9a50a136e7eae74a5146

**Pull request merged**
